name: Build and Release XrmToolBox

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*' # Trigger for new version tags (e.g., v1.0.0)

jobs:
  build-and-release:
    runs-on: windows-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2
      
    - name: Restore NuGet Packages
      run: nuget restore XrmToolBox.sln
      
    - name: Build Solution
      run: msbuild XrmToolBox.sln /p:Configuration=Release /p:Platform="Any CPU" /m
      
    - name: Zip Artifacts
      run: |
        Compress-Archive -Path "XrmToolBox\bin\Release\*" -DestinationPath "XrmToolBox-Release.zip"

    - name: Upload Action Artifact
      uses: actions/upload-artifact@v4
      with:
        name: XrmNightlyBox-Release
        path: XrmToolBox-Release.zip
      
    - name: Upload Release Asset
      uses: softprops/action-gh-release@v2
      if: always()
      with:
        tag_name: nightly
        name: Nightly Build
        files: XrmToolBox-Release.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
